
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import com.sun.jndi.ldap.Connection;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane; 
                                                        
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 123
 */
public class MainPage extends javax.swing.JFrame {
    java.sql.Connection conn=null;
    ResultSet rs=null;
    Statement st;
    
    private JFrame frame;
            

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UsernameTextBox = new javax.swing.JTextField();
        PasswordBox = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JToggleButton();
        ResetButton = new javax.swing.JToggleButton();
        LoginLabel = new javax.swing.JLabel();
        LoginLabel1 = new javax.swing.JLabel();
        CustomerEmployeeUsernameLabel = new javax.swing.JLabel();
        DealerEmployeeUsernameTextbox = new javax.swing.JTextField();
        CustomerEmployeePasswordLabel = new javax.swing.JLabel();
        CustomerEmployeePasswordBox = new javax.swing.JPasswordField();
        CustomerEmployeeLoginButton = new javax.swing.JToggleButton();
        CustomerEmployeeResetButton = new javax.swing.JToggleButton();
        DealerEmployeeLabel = new javax.swing.JLabel();
        DealerEmployeeUsernameLabel = new javax.swing.JLabel();
        DealerEmployeePasswordLabel = new javax.swing.JLabel();
        DealerEmployeeLoginButton = new javax.swing.JToggleButton();
        DealerEmployeeResetButton = new javax.swing.JToggleButton();
        CustumerEmployeeUsernameTextBox = new javax.swing.JTextField();
        managerLabel = new javax.swing.JLabel();
        CEmployeeLabel = new javax.swing.JLabel();
        DEmployeePasswordBox = new javax.swing.JPasswordField();
        DEmployeeLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Wholesale Management System ");
        setMinimumSize(new java.awt.Dimension(1380, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Wholesale Management System", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 48))); // NOI18N

        UsernameLabel.setText("Username");

        PasswordLabel.setText("Password");

        UsernameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextBoxActionPerformed(evt);
            }
        });

        LoginButton.setText("Login ");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        LoginLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginLabel.setText("Manager Login");
        LoginLabel.setToolTipText("");

        LoginLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LoginLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginLabel1.setText("Customer's Employee Login");
        LoginLabel1.setToolTipText("");

        CustomerEmployeeUsernameLabel.setText("Username");

        DealerEmployeeUsernameTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DealerEmployeeUsernameTextboxActionPerformed(evt);
            }
        });

        CustomerEmployeePasswordLabel.setText("Password");

        CustomerEmployeePasswordBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerEmployeePasswordBoxActionPerformed(evt);
            }
        });

        CustomerEmployeeLoginButton.setText("Login ");
        CustomerEmployeeLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerEmployeeLoginButtonActionPerformed(evt);
            }
        });

        CustomerEmployeeResetButton.setText("Reset");
        CustomerEmployeeResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerEmployeeResetButtonActionPerformed(evt);
            }
        });

        DealerEmployeeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DealerEmployeeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DealerEmployeeLabel.setText("Dealer's Employee Login");
        DealerEmployeeLabel.setToolTipText("");

        DealerEmployeeUsernameLabel.setText("Username");

        DealerEmployeePasswordLabel.setText("Password");

        DealerEmployeeLoginButton.setText("Login ");
        DealerEmployeeLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DealerEmployeeLoginButtonActionPerformed(evt);
            }
        });

        DealerEmployeeResetButton.setText("Reset");
        DealerEmployeeResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DealerEmployeeResetButtonActionPerformed(evt);
            }
        });

        CustumerEmployeeUsernameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustumerEmployeeUsernameTextBoxActionPerformed(evt);
            }
        });

        DEmployeePasswordBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEmployeePasswordBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Sample");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sample");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Sample");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(UsernameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(PasswordLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(managerLabel)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LoginButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ResetButton)
                                .addGap(46, 46, 46)
                                .addComponent(jButton1)))
                        .addGap(184, 184, 184)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CustomerEmployeeUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CustomerEmployeePasswordLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CustomerEmployeePasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CustumerEmployeeUsernameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LoginLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CEmployeeLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CustomerEmployeeLoginButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustomerEmployeeResetButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                                .addComponent(jButton2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(DealerEmployeeUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(DealerEmployeeUsernameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(DealerEmployeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(DealerEmployeePasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(DEmployeePasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(DEmployeeLabel)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(DealerEmployeeLoginButton)
                                .addGap(54, 54, 54)
                                .addComponent(DealerEmployeeResetButton)
                                .addGap(75, 75, 75)
                                .addComponent(jButton3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginLabel)
                    .addComponent(LoginLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameTextBox)
                    .addComponent(CustomerEmployeeUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustumerEmployeeUsernameTextBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel)
                    .addComponent(CustomerEmployeePasswordLabel)
                    .addComponent(CustomerEmployeePasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(managerLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CEmployeeLabel)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LoginButton)
                            .addComponent(ResetButton)
                            .addComponent(CustomerEmployeeLoginButton)
                            .addComponent(CustomerEmployeeResetButton)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(DealerEmployeeLabel)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DealerEmployeeUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DealerEmployeeUsernameTextbox))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DealerEmployeePasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DEmployeePasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DEmployeeLabel)
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DealerEmployeeLoginButton)
                                    .addComponent(DealerEmployeeResetButton))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 860, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
       
        UsernameTextBox.setText("");
        PasswordBox.setText("");
        
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void UsernameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextBoxActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
      
        PreparedStatement ps;
        ResultSet rs;
        String managerUsername, managerPassword;
        managerUsername=UsernameTextBox.getText().trim();
        managerPassword=String.valueOf(PasswordBox.getPassword());
        String query="SELECT * FROM `manager` WHERE `UserName`=? AND `Password`=?";
        try {
            ps=MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, managerUsername);
            ps.setString(2,managerPassword );
            rs=ps.executeQuery();
            
            if(rs.next())
            {
                //Functions and priveleges of manager.
                 this.dispose();
                 ManagerLogin c=new ManagerLogin();
                 c.setVisible(true);
                
            }
            else
            {
                if(UsernameTextBox.getText().equals("") || PasswordBox.getText().equals(""))
                {
                    managerLabel.setText("Enter value in the missing field(s)");
                }
                else
                {
                     managerLabel.setText("Invalid Username or Password");
                }
            
               
                
              UsernameTextBox.setText("");  
              PasswordBox.setText("");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void DealerEmployeeUsernameTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DealerEmployeeUsernameTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DealerEmployeeUsernameTextboxActionPerformed

    private void CustomerEmployeeLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerEmployeeLoginButtonActionPerformed
 PreparedStatement ps;
 ResultSet rs;
 String CEmployeeUsername, CEmployeePassword;
 CEmployeeUsername=CustumerEmployeeUsernameTextBox.getText().trim();
 CEmployeePassword=String.valueOf(CustomerEmployeePasswordBox.getPassword());
 String query="SELECT * FROM `customeremployee` WHERE `UserName`=? AND `Password`=?";
 
        try {
            ps=MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, CEmployeeUsername);
            ps.setString(2, CEmployeePassword);
            rs=ps.executeQuery();
            
            if(rs.next())
            {
               this.dispose();
               CustomerEmployeeFunctions c=new CustomerEmployeeFunctions();
               c.setVisible(true);
               
               
               
               
               
                //functions of Customer Employee
            }
            else
            {
              CustumerEmployeeUsernameTextBox.setText("");  
              CustomerEmployeePasswordBox.setText("");
              CEmployeeLabel.setText("Invalid Username or Password");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CustomerEmployeeLoginButtonActionPerformed

    private void CustomerEmployeeResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerEmployeeResetButtonActionPerformed
CustumerEmployeeUsernameTextBox.setText("");
CustomerEmployeePasswordBox.setText("");

        

    }//GEN-LAST:event_CustomerEmployeeResetButtonActionPerformed

    private void CustomerEmployeePasswordBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerEmployeePasswordBoxActionPerformed

        
// TODO add your handling code here:
    }//GEN-LAST:event_CustomerEmployeePasswordBoxActionPerformed

    private void DealerEmployeeLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DealerEmployeeLoginButtonActionPerformed
PreparedStatement ps;
 ResultSet rs;
 String DEmployeeUsername, DEmployeePassword;
 DEmployeeUsername=DealerEmployeeUsernameTextbox.getText().trim();
     DEmployeePassword=String.valueOf(DEmployeePasswordBox.getPassword());
     String query="SELECT * FROM `dealeremployee` WHERE `UserName`= ? AND `Password` =?";
     try {
            ps=MyConnection.getConnection().prepareStatement(query);
            ps.setString(1,DEmployeeUsername );
            ps.setString(2,DEmployeePassword );
            rs=ps.executeQuery();
            
            if(rs.next())
            {
               this.dispose();
               DealerEmployeeFunctions a=new DealerEmployeeFunctions();
               a.setVisible(true);
                //functions and priveleges of Dealer's Employee
            }
            else
            {
              DealerEmployeeUsernameTextbox.setText("");  
              DEmployeePasswordBox.setText("");
              DEmployeeLabel.setText("Invalid Username or Password");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        



    }//GEN-LAST:event_DealerEmployeeLoginButtonActionPerformed

    private void DealerEmployeeResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DealerEmployeeResetButtonActionPerformed

DealerEmployeeUsernameTextbox.setText("");  
              DEmployeePasswordBox.setText("");
    }//GEN-LAST:event_DealerEmployeeResetButtonActionPerformed

    private void CustumerEmployeeUsernameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustumerEmployeeUsernameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustumerEmployeeUsernameTextBoxActionPerformed

    private void DEmployeePasswordBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEmployeePasswordBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DEmployeePasswordBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

this.dispose();
ManagerLogin a=new ManagerLogin();
a.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();
CustomerEmployeeFunctions a=new CustomerEmployeeFunctions();
a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

this.dispose();
DealerEmployeeFunctions a=new DealerEmployeeFunctions();
a.setVisible(true);        

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
private void CloseMe()
{
    WindowEvent meClose=new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(meClose);
    
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CEmployeeLabel;
    private javax.swing.JToggleButton CustomerEmployeeLoginButton;
    private javax.swing.JPasswordField CustomerEmployeePasswordBox;
    private javax.swing.JLabel CustomerEmployeePasswordLabel;
    private javax.swing.JToggleButton CustomerEmployeeResetButton;
    private javax.swing.JLabel CustomerEmployeeUsernameLabel;
    private javax.swing.JTextField CustumerEmployeeUsernameTextBox;
    private javax.swing.JLabel DEmployeeLabel;
    private javax.swing.JPasswordField DEmployeePasswordBox;
    private javax.swing.JLabel DealerEmployeeLabel;
    private javax.swing.JToggleButton DealerEmployeeLoginButton;
    private javax.swing.JLabel DealerEmployeePasswordLabel;
    private javax.swing.JToggleButton DealerEmployeeResetButton;
    private javax.swing.JLabel DealerEmployeeUsernameLabel;
    private javax.swing.JTextField DealerEmployeeUsernameTextbox;
    private javax.swing.JToggleButton LoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JLabel LoginLabel1;
    private javax.swing.JPasswordField PasswordBox;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JToggleButton ResetButton;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel managerLabel;
    // End of variables declaration//GEN-END:variables
}
