/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 123
 */
public class SupplierOptions extends javax.swing.JFrame {
    ManagerLogin m;

    /**
     * Creates new form SupplierOptions
     */
    public SupplierOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SupplierOptionsButton = new javax.swing.JLabel();
        GobackButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        AddSupplierButton = new javax.swing.JButton();
        DeleteSupplierButton = new javax.swing.JButton();
        UpdateSupplierbutton = new javax.swing.JButton();
        SearchSupplierButton = new javax.swing.JButton();
        ProductOptionsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SupplierOptionsButton.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        SupplierOptionsButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SupplierOptionsButton.setText("Supplier Options");

        GobackButton.setText("<--- Go back");
        GobackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GobackButtonActionPerformed(evt);
            }
        });

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        AddSupplierButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AddSupplierButton.setText("Add Supplier");
        AddSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSupplierButtonActionPerformed(evt);
            }
        });

        DeleteSupplierButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DeleteSupplierButton.setText("Delete Supplier");
        DeleteSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSupplierButtonActionPerformed(evt);
            }
        });

        UpdateSupplierbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UpdateSupplierbutton.setText("Update Supplier");
        UpdateSupplierbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSupplierbuttonActionPerformed(evt);
            }
        });

        SearchSupplierButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SearchSupplierButton.setText("Search Supplier");
        SearchSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchSupplierButtonActionPerformed(evt);
            }
        });

        ProductOptionsButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ProductOptionsButton.setText("Product Options");
        ProductOptionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductOptionsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GobackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutButton))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(SupplierOptionsButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductOptionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AddSupplierButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UpdateSupplierbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SearchSupplierButton)
                                    .addComponent(DeleteSupplierButton))))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GobackButton)
                    .addComponent(LogoutButton))
                .addGap(18, 18, 18)
                .addComponent(SupplierOptionsButton)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddSupplierButton)
                    .addComponent(DeleteSupplierButton))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateSupplierbutton)
                    .addComponent(SearchSupplierButton))
                .addGap(30, 30, 30)
                .addComponent(ProductOptionsButton)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSupplierButtonActionPerformed
     this.dispose();
       DeleteSupplier ml=new DeleteSupplier();
        ml.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteSupplierButtonActionPerformed

    private void GobackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GobackButtonActionPerformed

        if (m.a==1)
        {
        this.dispose();
        ManagerLogin ml=new ManagerLogin();
        ml.setVisible(true);
        m.a=m.a-1;
        }
        else
        {
            this.dispose();
            DealerEmployeeFunctions dml=new DealerEmployeeFunctions();
            dml.setVisible(true);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_GobackButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
       this.dispose();
       MainPage mp=new MainPage();
       mp.setVisible(true);
        

// TODO add your handling code here:
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void AddSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSupplierButtonActionPerformed
      
        this.dispose();
       AddSupplier mp=new AddSupplier();
       mp.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_AddSupplierButtonActionPerformed

    private void UpdateSupplierbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSupplierbuttonActionPerformed

        
this.dispose();
       UpdateSupplier mp=new UpdateSupplier();
       mp.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_UpdateSupplierbuttonActionPerformed

    private void SearchSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchSupplierButtonActionPerformed

        this.dispose();
       SearchSupplier mp=new SearchSupplier();
       mp.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_SearchSupplierButtonActionPerformed

    private void ProductOptionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductOptionsButtonActionPerformed
        
        this.dispose();
        ProductOptions  po=new ProductOptions();
        po.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ProductOptionsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSupplierButton;
    private javax.swing.JButton DeleteSupplierButton;
    private javax.swing.JButton GobackButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ProductOptionsButton;
    private javax.swing.JButton SearchSupplierButton;
    private javax.swing.JLabel SupplierOptionsButton;
    private javax.swing.JButton UpdateSupplierbutton;
    // End of variables declaration//GEN-END:variables
}
