
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 123
 */
public class UpdateSupplier extends javax.swing.JFrame {

    /**
     * Creates new form UpdateSupplier
     */
    public UpdateSupplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GobackButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        SupplierOptionsButton = new javax.swing.JLabel();
        NameTextbox = new javax.swing.JTextField();
        IDTextbox = new javax.swing.JTextField();
        PhoneNumberTextbox = new javax.swing.JTextField();
        invalid2 = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        IDLabel = new javax.swing.JLabel();
        ResetButton = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        QuantityLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GobackButton.setText("<--- Go back");
        GobackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GobackButtonActionPerformed(evt);
            }
        });

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        SupplierOptionsButton.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        SupplierOptionsButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SupplierOptionsButton.setText("Update Supplier");

        NameTextbox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        IDTextbox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        PhoneNumberTextbox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PhoneNumberTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberTextboxActionPerformed(evt);
            }
        });

        invalid2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        UpdateButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        IDLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        IDLabel.setText("Enter Supplier ID to update:");

        ResetButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        NameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NameLabel.setText("Name:");

        QuantityLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        QuantityLabel.setText("Phone Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GobackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 760, Short.MAX_VALUE)
                .addComponent(LogoutButton))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(SupplierOptionsButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(248, 248, 248)
                                        .addComponent(UpdateButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ResetButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addComponent(IDLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(IDTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QuantityLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PhoneNumberTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(107, 107, 107))
                            .addComponent(invalid2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GobackButton)
                    .addComponent(LogoutButton))
                .addGap(18, 18, 18)
                .addComponent(SupplierOptionsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDLabel)
                            .addComponent(IDTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(UpdateButton)
                                .addComponent(ResetButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PhoneNumberTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QuantityLabel))
                                .addGap(112, 112, 112))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(invalid2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(266, 266, 266)))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GobackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GobackButtonActionPerformed

        this.dispose();
        SupplierOptions ml=new SupplierOptions();
        ml.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_GobackButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        this.dispose();
        MainPage mp=new MainPage();
        mp.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void PhoneNumberTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberTextboxActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed

        //update karlo bhai

        String DealerID, DealerName, DealerPhoneNumber;
        DealerID=IDTextbox.getText();
        DealerName=NameTextbox.getText();
        DealerPhoneNumber=PhoneNumberTextbox.getText();

        if(DealerName.equals("") || DealerPhoneNumber.equals("") )
        {
            JOptionPane.showMessageDialog(null, "Please enter values in the missing fields");
            return;
        }
        if(DealerID.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Customer ID");
            return;

        }
         try {
     Integer.parseInt(DealerPhoneNumber);
        }
catch (NumberFormatException e)
{
   JOptionPane.showMessageDialog(null, "Please enter valid phone Number");
     PhoneNumberTextbox.setText("");
   return;
}
           
           try {
     Integer.parseInt(DealerID);
        }
catch (NumberFormatException e)
{
   JOptionPane.showMessageDialog(null, "Please enter numeric value for ID");
     IDTextbox.setText("");
   return;
}
           
            if ( DealerPhoneNumber.startsWith("-"))
       {
             JOptionPane.showMessageDialog(null, "Please enter a right numeric value in Price");
   return;
       }
             if ( DealerID.startsWith("-"))
       {
             JOptionPane.showMessageDialog(null, "Please enter a right numeric value in Price");
   return;
       }
    
            
        PreparedStatement ps;

        try {
            String query="UPDATE `dealer` SET `DealerName`=?, `DealerPhoneNumber`=? WHERE `DealerID`=?";
            ps=MyConnection.getConnection().prepareStatement(query);

            ps.setString(1, DealerName);
            ps.setString(2, DealerPhoneNumber);
            ps.setString(3, DealerID);

            if(ps.executeUpdate()>0)
            {
                IDTextbox.setText("");
                NameTextbox.setText("");
                PhoneNumberTextbox.setText("");

                JOptionPane.showMessageDialog(null, "Product Updated succesfully");
            }
            else
            {

                invalid2.setText("No such Dealer ID exists");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed

        IDTextbox.setText("");
        NameTextbox.setText("");
        PhoneNumberTextbox.setText("");
     
        invalid2.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_ResetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GobackButton;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDTextbox;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextbox;
    private javax.swing.JTextField PhoneNumberTextbox;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JButton ResetButton;
    private javax.swing.JLabel SupplierOptionsButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel invalid2;
    // End of variables declaration//GEN-END:variables
}
